### ISSUE TITLE
Unsure how to use this

### ISSUE THREAD

**Issue by sibendu** [RishikeshDarandale/soap-server-lambda#129]
Hi Rishikesh,
I am unsure how to use this. My node skill is very minimal. Is it possible to extend the instructions please?
Thank you.

**Comment by RishikeshDarandale** [comment]
Hi @sibendu ,
This application try to expose the SOAP service deployed to AWS lambda and managed via serverless framework.

You can refer the [README.md](https://github.com/RishikeshDarandale/soap-server-lambda/blob/master/README.md) or [example](https://github.com/RishikeshDarandale/soap-server-lambda/tree/master/example)

**Comment by sibendu** [comment]
Thank you. Should I use the serverless.yml in the example as a CodeBuild project?

**Comment by RishikeshDarandale** [comment]
First test your work with `npx sls deploy` command, this will create all the resources needed (Lambda, API gateway, etc). Then you can refer [this](https://www.serverless.com/blog/cicd-for-serverless-part-2) to integrate with CodeBuild.
